CREATE TABLE t(id INT, x INT);
INSERT INTO t(id, x) VALUES (1, 5);
INSERT INTO t(id, x) VALUES (2, 1);
INSERT INTO t(id, x) VALUES (3, 3);
INSERT INTO t(id, x) VALUES (4, 2);
INSERT INTO t(id, x) VALUES (5, 4);
INSERT INTO t(id, x) VALUES (6, 6);
SELECT * FROM t ORDER BY x ASC LIMIT 5
